"""add created_by to business resources

Revision ID: be01aff31738
Revises: b8425438e477
Create Date: 2026-06-14 08:33:18.159508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be01aff31738'
down_revision: Union[str, Sequence[str], None] = 'b8425438e477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_deployments_created_by_users', 'deployments', 'users', ['created_by'], ['id'])
    op.add_column('eval_runs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_eval_runs_created_by_users', 'eval_runs', 'users', ['created_by'], ['id'])
    op.add_column('model_versions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_model_versions_created_by_users', 'model_versions', 'users', ['created_by'], ['id'])
    op.add_column('training_jobs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_training_jobs_created_by_users', 'training_jobs', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_training_jobs_created_by_users', 'training_jobs', type_='foreignkey')
    op.drop_column('training_jobs', 'created_by')
    op.drop_constraint('fk_model_versions_created_by_users', 'model_versions', type_='foreignkey')
    op.drop_column('model_versions', 'created_by')
    op.drop_constraint('fk_eval_runs_created_by_users', 'eval_runs', type_='foreignkey')
    op.drop_column('eval_runs', 'created_by')
    op.drop_constraint('fk_deployments_created_by_users', 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'created_by')
    # ### end Alembic commands ###
